server:
  port: 8082
  servlet:
    context-path: /order-service
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/orders
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
